version: '3.7'

services:
  dbin28minutes:
    restart: always
    image: percona:5.7.26
    volumes:
      - mysql-data-28minutes:/var/lib/mysql
    container_name: in28minutesdb
    ports:
      - "3320:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--thread-pool-size=16"
        
volumes:
  mysql-data-28minutes:
        

